// Access to the SPIR-V blobs compiled by the Makefile and linked into the executable.
// The table itself is generated by tools/embed_shaders.sh. Shaders
// are never loaded from disk at runtime.
#ifndef BLACK_HOLE_SHADERS_EMBEDDED_H
#define BLACK_HOLE_SHADERS_EMBEDDED_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ShaderBlob {
    const char*          name;  // e.g. "probe.comp"
    const unsigned char* data;
    unsigned             size;  // bytes
} ShaderBlob;

extern const ShaderBlob g_shaders[];
extern const unsigned   g_shader_count;

// Returns NULL when no blob of that name was linked in.
const ShaderBlob* shader_blob(const char* name);

#ifdef __cplusplus
}
#endif

#endif
