#!/bin/sh
# Emit a C translation unit embedding every SPIR-V blob passed on the command line.
# Usage: embed_shaders.sh <out.c> <in1.spv> [in2.spv ...]
#
# The generated file defines one static array per blob plus a g_shaders table that
# shader_blob() in src/render/shaders_embedded.h looks up by name. Blobs are named
# after the source shader with the .spv stripped: "terrain.vert", "bloom.comp".

set -e

out=$1
shift

if [ -z "$out" ] || [ $# -eq 0 ]; then
    echo "usage: embed_shaders.sh <out.c> <in.spv> [...]" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"

{
    echo '/* Generated by tools/embed_shaders.sh. Do not edit. */'
    echo '#include "render/shaders_embedded.h"'
    echo
} > "$out"

# One array per blob.
for spv in "$@"; do
    base=$(basename "$spv" .spv)
    sym="spv_$(echo "$base" | tr '.-' '__')"
    # xxd also emits a <sym>_len; the table below uses sizeof, so drop it rather than ship an
    # unused symbol that -Wall would flag (spec A1 requires a warning-free build).
    xxd -i -n "$sym" "$spv" \
        | sed 's/^unsigned char/static const unsigned char/' \
        | sed '/^unsigned int .*_len = /d' >> "$out"
    echo >> "$out"
done

# The lookup table.
{
    echo 'const ShaderBlob g_shaders[] = {'
    for spv in "$@"; do
        base=$(basename "$spv" .spv)
        sym="spv_$(echo "$base" | tr '.-' '__')"
        printf '    { "%s", %s, sizeof(%s) },\n' "$base" "$sym" "$sym"
    done
    echo '};'
    echo
    printf 'const unsigned g_shader_count = %d;\n' "$#"
} >> "$out"
